### ISSUE TITLE
latest version marked as 1.20.1 compatible but its not

### ISSUE THREAD

**Issue by Rozbiynk** [UltimatChamp/FabricBetterGrass#11]
**Describe the bug**
https://modrinth.com/mod/fabricbettergrass/version/1.0.3+1.20.6 marked as 1.20-1.20.6 compatible, but i cant load 1.20.1 with this version

**To Reproduce**
1. Download 1.0.3
2. launch minecraft 1.20.1
3. crash

**Expected behavior**
Work on marked versions

**Desktop (please complete the following information):**
 - OS: windows 11
 - Minecraft 1.20.1
 - Fabric Loader version 0.15.11
 - Mods fabric api and midnight lib
 - Version 1.0.3

**Comment by UltimatChamp** [comment]
Can you provide logs? _(preferably upload it to mclo.gs)_

**Comment by UltimatChamp** [comment]
Fixed! This version was supposed to support `1.20`-`1.20.6` but the new automated publishing script uploaded the wrong file, making this version crash!

_this means there was a similar crash with all the other mc versions too_ 😅
