### ISSUE TITLE
Crash on MC1.20.1

### ISSUE THREAD

**Issue by nickkeane** [UltimatChamp/FabricBetterGrass#14]
**Describe the bug**
Minecraft fails to launch with error:

`java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bettergrass'`

See Logs below

**To Reproduce**
1. Install MC1.20.1, LWJGL 3.3.1, and Fabric Loader 0.15.11.
2. Install Mods Fabric API, YetAnotherConfigLib, and FabricBetterGrass
3. Launch Minecraft

**Expected behavior**
Minecraft should launch to main menu

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.20.1
 - Fabric Loader 0.15.11
 - Mods [Fabric API 0.92.2+1.20.1, YetAnotherConfigLib 3.5.0+1.20.1-fabric]
 - Version 1.013+1.20.6

**Additional context**
Logs - https://mclo.gs/hwob90x

**Comment by nickkeane** [comment]
To add, the issue only seems to be occurring with my MC1.20.1 Fabric instance. My MC1.20.6 and MC1.21 Fabric setups seem to be working with this mod.

**Comment by UltimatChamp** [comment]
The crash was caused due to an incompatibility with Java 17; Java 21 worked fine.
_Thanks for letting me know!_

**Comment by nickkeane** [comment]
This looks wrong:

```
def targetJavaVersion
if ("${project.version}".contains("1.20"))
    targetJavaVersion = 17
else
    targetJavaVersion = 21
```

Mojang (unfortunately) did the Java transition on a minor version, MC1.20.5, not on 1.21.
MC1.20.4 and earlier use 17, MC1.20.5 and up use 21.
