### ISSUE TITLE
Crash when going to ESC menu after updating

### ISSUE THREAD

**Issue by vico93** [UltimatChamp/FabricBetterGrass#18]
**Describe the bug**
Just got [this crash](https://gist.github.com/vico93/9f81f4b2c7df01fa026bb932b368ca39) when trying to press ESC after connecting in a server after updating both FabricBetterGrass and adding a forked version of [BorderlessMining](https://github.com/comp500/BorderlessMining) by @sky-is-winning to my modpack. Seems to be a mixin error.

**Desktop**
 - OS: Windows 10 x64
 - Minecraft 1.21
 - Fabric Loader 0.16.0-1.21
 - Mods Fabric API 0.100.7+1.21, Borderless Mining 1.1.10-dev.4c1df01+1.21, FabricBetterGrass 1.0.18+1.21
 - Version 1.0.18

**Comment by UltimatChamp** [comment]
You should inform @sky-is-winning about the crash, instead!
Other mods too, that add a config option on the vanilla video settings screen, will face a similar crash.

**Comment by sky-is-winning** [comment]
Yup, same issue as I had with Iris.

**Comment by UltimatChamp** [comment]
@sky-is-winning you can change the mixin priority for the time-being, to make your fork compatible with other mods.

```diff
- @Mixin(VideoOptionsScreen.class)
+ @Mixin(value = VideoOptionsScreen.class, priority = 990)
```
it seems that you are replacing every option from the video settings screen, which leads to a mixin  priority conflict.

**Comment by vico93** [comment]
> @sky-is-winning you can change the mixin priority for the time-being, to make your fork compatible with other mods.
> 
> ```diff
> - @Mixin(VideoOptionsScreen.class)
> + @Mixin(value = VideoOptionsScreen.class, priority = 990)
> ```
> 
> it seems that you are replacing every option from the video settings screen, which leads to a mixin priority conflict.

I never imagined Sky was doing that... i thoguht that mod was just to make the game fullscreen to be borderless windowed :P

**Comment by UltimatChamp** [comment]
The existing mixin implementation in Borderless Mining doesn't do that and it's perfectly compatible with other mods.
sky-is-wining have to correct their mixin.

**Comment by sky-is-winning** [comment]
> The existing mixin implementation in Borderless Mining doesn't do that and it's perfectly compatible with other mods. sky-is-wining have to correct their mixin.
> 
> _It is just a simple mixin to add a borderless fullscreen option to the vanilla video settings screen..._

I'm not a java mod dev lol, I just wanted my game to not crash when using this mod. My bodged fix works fine for me.
If you want to improve it, feel free to.
