### ISSUE TITLE
Game crash when starting a world with fabric better grass installed

### ISSUE THREAD

**Issue by cobaltlol2** [UltimatChamp/FabricBetterGrass#21]
**Describe the bug**
My game crashes whenever I start a world with the mod enabled with the error being Tessellating block in world - Indium Renderer.

**To Reproduce**
1. Have the mod on
2. Presumably also have some sort of conflicting mod other than just fabric better grass
3. Launch MC and start a world
4. Error

**Expected behavior**
I would be able to play the game normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Minecraft 1.21
 - Fabric Loader version 0.16.0
 - Mods https://modrinth.com/modpack/true-vanilla+/version/n39c0y0I (my modpack page with all the mods)
 - Version 1.0.21

**Additional context**
It's most likely an incompatability, as this didn't happen before.
Crash log: https://mclo.gs/vwIdVex
latest.log: https://mclo.gs/BXMnwod

**Comment by cobaltlol2** [comment]
> 0.100.8+1.21

Will this be fixed on newest fabric api versions cause I have a few mods that can't run the older fabric api's?

**Comment by UltimatChamp** [comment]
There's nothing to be fixed in Fabric API, it's **Indium** that has to fix compat with Fabric API 0.101+.

**Comment by UltimatChamp** [comment]
Use **Indium** `1.0.35+mc1.21` with the latest versions of **Fabric API**
